dist: trusty

language: python

python:
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - ruby

install:
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - brew install mecab mecab-ipadic

script:
  - LD_LIBRARY_PATH="$HOME/.linuxbrew/lib" rake test
